name: despliegue

on: [push,pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: make file
      run: touch hola.txt
    - name: set text
      run: echo "mi nombre es jonh-of" >> hola.txt
    - name: read file
      run: cat hola.txt



   
  
  deploy2:
    runs-on: ubuntu-latest
    needs: [deploy]

    steps:
    
    - name: ls
      run: ls

